Revert "Merge pull request #11 from malcolmlett/dependabot/bundler/just-the-docs-0.10.1"
It caused error:
sass-embedded-1.89.2-x86_64-linux-gnu requires ruby version >= 3.2, which is
incompatible with the current version, 3.1.7
Error: The process '/opt/hostedtoolcache/Ruby/3.1.7/x64/bin/bundle' failed with exit code 5

This reverts commit 2f8f2d48f4b4d14ed60a5b272c9ccf67c8f54f40, reversing
changes made to 3e166b7c2b1aa21214a92d748ebaad93b62013e8.